blogs/urls.py
from django.urls import path
from . import views

app_name = 'blogs'
urlpatterns = [
    path('', views.index, name='index'),
    path('detail/<int:blog_id>/', views.detail, name='detail')
]

django_blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blogs.urls')),
]

blogs/models.py
from django.db import models

class Blog(models.Model):
    title = models.CharField(blank=False, null=False, max_length=150)
    text = models.TextField(blank=True)
    created_datetime = models.DateTimeField(auto_now_add=True)
    updated_datetime = models.DateTimeField(auto_now=True)

    def  __str__(self):
        return self.title

blogs/views.py
from django.shortcuts import render
from .models import Blog

def index(request):
    blogs = Blog.objects.order_by('-created_datetime')
    return render(request, 'blogs/index.html', {'blogs': blogs})


def detail(request, blog_id):
    blog = Blog.objects.get(id=blog_id)
    return render(request, 'blogs/detail.html', {'blog': blog})

blogs/templates/blogs/detail.html
<!DOCTYPE html>
<html>
    <head>
        <title>ブログアプリ</title>
    </head>
    <body>
        <h1 style="text-align: center;">{{ blog.title }}</h1>
        <div style="width: 70%; margin: 0px auto">
            <div>
                <div style="margin: 60px 20px;">
                    {{ blog.text }}
                    {{ blog.created_datetime }}
                    {{ blog.updated_datetime }}
                    <a href="{% url 'blogs:index' %}">戻る</a>
                </div>
            </div>
        </div>
    </body>
</html>

blogs/templates/blogs/index.html
<!DOCTYPE html>
<html>
    <head>
        <title>ブログ管理サイト</title>
    </head>
    <body>
        <h1 style="text-align: center;">My Blog</h1>
        <div style="width: 70%; margin: 0px auto;">
            <hr>
            {% for blog in blogs %}
            <div>
                <h3>{{ blog.title }}</h3>
                <div>{{ blog.text |truncatechars:100}}</div>
                <div style="text-align: right;">
                    <a href="{% url 'blogs:detail' blog_id=blog.id %}">記事を読む</a>
                </div>
            </div>
            <hr>
            {% endfor %}
        </div>
    </body>
</html>